parameters:
#    polytech_projet_transversal.example.class: Polytech\ProjetTransversalBundle\Example

services:
#    polytech_projet_transversal.example:
#        class: %polytech_projet_transversal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]